server:
  port: 8099
  servlet:
    context-path: /

# 配置日志文件路径，这个不配置也行，默认就是这个
#logging:
#  config: classpath:logback-spring.xml

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/play?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: root

# Mybatis-Plus 配置
mybatis-plus:
  # 配置 xxxMapper.xml 的路径
  mapper-locations: classpath*:mapper/*.xml
  # 配置了之后，xml 文件中 sql 部分就不用写全限定名，可以直接使用类名了
  type-aliases-package: org.demo.entity
  configuration:
    # 开启自动驼峰规则映射，就是表名如果有下划线在 java 中会转成驼峰
    map-underscore-to-camel-case: true
  global-config:
    # 控制台是否展示 Mybatis-Plus 的 logo，这里就不展示了
    banner: false
    db-config:
      # 所有表的逻辑删除字段名
      logic-delete-field: idDeleted
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑删除未删除值
      logic-not-delete-value: 0
#      # 插入策略，插入数据时判断，如果字段不是 null 并且不是 空字符串，就插入
#      insert-strategy: not_empty
#      # 更新策略，更新数据时判断，如果字段不是 null 并且不是 空字符串，就插入
#      update-strategy: not_empty

